### ISSUE TITLE
Saludos

### ISSUE THREAD

**Issue by seguis** [Manfred047/laravel-quasar#18]
Buen dia amigo, su proyecto quiere decir que posee las mismas funcionalidades de Quasar, solo que ahora esta funcionado con laravel?

**Comment by Manfred047** [comment]
si, asi es, aunque la función de ssr no la he testeado, pero funciona perfectamente en modo SPA

**Comment by seguis** [comment]
Posees algun grupo de amigos donde tengan un proyecto, acabo de terminar un curso de laravel, pero en un grupo en el facebook revise una app hecha en Quasar y me encanto, sobre todo el tema multi-plataforma. Actualmente estoy aprendiendo, antes de realizar un proyecto personal que pienso hacer para mi trabajo, me ahorrara muchisimas tareas cuando por fin lo pueda realizar, pero antes quiero aprender para saber hacerlo de la forma correcta

**Comment by Manfred047** [comment]
Actualmente no, pero me puedes contactar por discord para dudas puntuales, e intentaré ayudarte en lo mejor posible, de igual manera te recomiendo que revises grupos por facebook.

discord: Manfred#2246

**Comment by seguis** [comment]
Te envie una solicitud
