### ISSUE TITLE
Issue logging in

### ISSUE THREAD

**Issue by salvationarinze** [Manfred047/laravel-quasar#22]
In trying to login, this route is called: **http://127.0.0.1:8000/api/v1/oauth/token** but I get this error: 
```
{
  "error": "method_not_allowed",
  "code": 405,
  "hint": "Method Not Allowed",
  "message": "The method POST is not allowed."
}
```
I just can't get the default app logging in or even registering, same error. Even when I started the laravel server, it's just not working. Please help.

I checked and the routing is handled by quasar. How do I point to laravel's routes?

**Comment by Manfred047** [comment]
the php server not working with headers (ajax header), you need to configure the apache v-host, and windows host, then set special route for laravel api.

for example:

windows host: `127.0.0.1 lq.test`

apache v-host:

`<VirtualHost *:80>
    ServerAdmin manfred@manfred047.com
    DocumentRoot "C:/xampp/htdocs/laravel-quasar/public"
    ServerName lq-test
    ServerAlias lq.test
</VirtualHost>`

Then, when you execute the quasar dev, Quasar runs at the lq.test:8000 and laravel api in lq.test.

don't forget config the `.env.quasar.development`, you can see the `.env.quasar.development.example`

**Comment by salvationarinze** [comment]
That has been done. Quasar runs at the lq.test:8000 but visiting lq.test display the homepage and doesn't run the **laravel api**. 
Also visiting http://lq.test/api/v1/test for a test json route I created returns the same "405 Method not Allowed" Error. 

Please what am I doing wrong?

**Comment by Manfred047** [comment]
You has two options, first, use "Postman" for request and add the ajax headers `X-Requested-With
: XMLHttpRequest` or comment (not recommended) exception rule in `VerifyAjaxRequest` middleware (line 27).

**Comment by salvationarinze** [comment]
Done and it's a 400 Bad Request "Bad Request Your browser sent a request that this server could not understand."
