### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by 3kynox** [Manfred047/laravel-quasar#9]
Hey! Thanks for your work here!

I was looking to integrate latest Quasar with latest Laravel and Spark (Nova later), it looks like almost everything are done here. Did you made any blog / docs where you explain the process?

I would like to create a branch and adapt this with Spark but as the Spark repository is private, it should be hard to do.

Anyway, I'll do it locally and give you back the results.

2 Additional questions:
- Is it the UMD version of Quasar? Or the Starter
- Did you tried to build your app native (Electron mac/win/nux app) or iOS / Android?

Cheers.

**Comment by Manfred047** [comment]
No, I didn't write the process, only how to use it (readme.md). This Quasar implementation works like Quasar CLI (Starter Kit), with some modifications (using Laravel mix).

For now, it only works with web SPA, but this implementation should work perfectly with Starter Kit functionality.

I want to implement the Nuxt.js soon.

Thanks for using this repository, and I'll be looking forward to your test results.

**Comment by 3kynox** [comment]
Fine.

I remember Nuxt is used mostly to get Server Side Rendering.
If you use Quasar starter kit, I saw they integrated SSR already out of the box recently:
https://quasar-framework.org/guide/index.html on the comparison table

So no need of Nuxt normally?
